options:
  tune:
    - QsSeeThreshold

tuning:
  # Search options:

  - name: QsSeeThreshold
    value: 104

  - name: QsPruneMargin
    value: 650

  - name: TimeextScoreDropThreshold
    value: 20

  - name: TimeextHistorySize
    value: 6