[workspace]
resolver = "2"

members = [
    "engine",
    "fathomrs",
    "gensets",
    "genmagics",
    "cputrainer",
    "gputrainer",
    "selfplay",
    "sprt",
    "traincommon",
    "tournament",
    "tuner",
]

[profile.release]
codegen-units = 16
lto = "thin"
