[package]
name = "sprt"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
velvet = { path = "../engine" }

rand = "0.8.5"
core_affinity = "0.8.1"
libm = "0.2.8"
thread-priority = "1.1.0"
