name: Release

on:
  push:
    tags: "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linux-musl target
        run: |
          rustup target add x86_64-unknown-linux-musl

      - name: Build x86_64-avx2
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static,-bmi2 -Ctarget-cpu=x86-64-v3"
        run: |
          cargo build --release --target x86_64-unknown-linux-musl --bin velvet
          strip target/x86_64-unknown-linux-musl/release/velvet
          mv target/x86_64-unknown-linux-musl/release/velvet velvet-linux-x86_64-avx2

      - name: Build x86_64-sse4-popcnt
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v2"
        run: |
          rm -rf target
          cargo build --release --target x86_64-unknown-linux-musl --bin velvet
          strip target/x86_64-unknown-linux-musl/release/velvet
          mv target/x86_64-unknown-linux-musl/release/velvet velvet-linux-x86_64-sse4-popcnt

      - name: Build x86_64-nopopcnt
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static"
        run: |
          rm -rf target
          cargo build --release --target x86_64-unknown-linux-musl --bin velvet
          strip target/x86_64-unknown-linux-musl/release/velvet
          mv target/x86_64-unknown-linux-musl/release/velvet velvet-linux-x86_64-nopopcnt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: velvet-linux
          path: velvet-*

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build x86_64-avx2
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static,-bmi2 -Ctarget-cpu=x86-64-v3"
        run: |
          cargo build --release --bin velvet
          mv .\target\release\velvet.exe velvet-windows-x86_64-avx2.exe

      - name: Build x86_64-see-popcnt
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static -Ctarget-cpu=x86-64-v2"
        run: |
          rm target -r -fo
          cargo build --release --bin velvet
          mv .\target\release\velvet.exe velvet-windows-x86_64-sse4-popcnt.exe

      - name: Build x86_64-nopopcnt
        env:
          RUSTFLAGS: "-Ctarget-feature=+crt-static"
        run: |
          rm target -r -fo
          cargo build --release --bin velvet
          mv .\target\release\velvet.exe velvet-windows-x86_64-nopopcnt.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: velvet-windows
          path: velvet*.exe

  release:
    if: github.repository == 'mhonert/velvet-chess'
    needs: [build-linux, build-windows]
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: velvet-linux

      - uses: actions/download-artifact@v2
        with:
          name: velvet-windows

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          ls -l
          chmod +x velvet-linux-x86_64-avx2
          chmod +x velvet-linux-x86_64-sse4-popcnt
          chmod +x velvet-linux-x86_64-nopopcnt
          mv velvet-windows-x86_64-avx2.exe velvet-${tag_name}-x86_64-avx2.exe
          mv velvet-windows-x86_64-sse4-popcnt.exe velvet-${tag_name}-x86_64-sse4-popcnt.exe
          mv velvet-windows-x86_64-nopopcnt.exe velvet-${tag_name}-x86_64-nopopcnt.exe
          mv velvet-linux-x86_64-avx2 velvet-${tag_name}-x86_64-avx2
          mv velvet-linux-x86_64-sse4-popcnt velvet-${tag_name}-x86_64-sse4-popcnt
          mv velvet-linux-x86_64-nopopcnt velvet-${tag_name}-x86_64-nopopcnt
          sha256sum velvet-* > checksums.txt
          echo "$tag_name" > release_description.txt
          cat artifacts/release_notes.md >> release_description.txt
          hub release create -a "checksums.txt#Checksums" \
                             -a "velvet-${tag_name}-x86_64-avx2.exe#Velvet - Windows (x86_64 - AVX2)" \
                             -a "velvet-${tag_name}-x86_64-sse4-popcnt.exe#Velvet - Windows (x86_64 - SSE4.2+POPCNT)" \
                             -a "velvet-${tag_name}-x86_64-nopopcnt.exe#Velvet - Windows (x86_64 - No POPCNT)" \
                             -a "velvet-${tag_name}-x86_64-avx2#Velvet - Linux (x86_64 - AVX2)" \
                             -a "velvet-${tag_name}-x86_64-sse4-popcnt#Velvet - Linux (x86_64 - SSE4.2+POPCNT)" \
                             -a "velvet-${tag_name}-x86_64-nopopcnt#Velvet - Linux (x86_64 - No POPCNT)" \
                             -F release_description.txt "$tag_name"
