name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          rustup override set 1.66.0
          cargo test --no-default-features --release -p velvet --lib
