name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Switch to nightly toolchain
        run: |
          rustup override set nightly-2021-10-06

      - name: Run tests
        run: |
          cargo test --release
